---
- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'

- name: Add Grafana repository
  copy:
    dest: /etc/apt/sources.list.d/grafana.list
    content: |
      deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main
    owner: root
    group: root
    mode: '0644'

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Ensure Grafana is enabled and started
  service:
    name: grafana-server
    state: started
    enabled: true
